"""Changes on the counseling session table

Revision ID: 05358dff8fa2
Revises: b21ea9f87ea7
Create Date: 2026-08-31 21:23:18.499609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05358dff8fa2'
down_revision = 'b21ea9f87ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counseling_sessions', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('session_status',
               existing_type=mysql.ENUM('Active', 'Completed', 'Cancelled'),
               type_=sa.Enum('Pending', 'Active', 'Completed', 'Cancelled', name='session_status_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counseling_sessions', schema=None) as batch_op:
        batch_op.alter_column('session_status',
               existing_type=sa.Enum('Pending', 'Active', 'Completed', 'Cancelled', name='session_status_enum'),
               type_=mysql.ENUM('Active', 'Completed', 'Cancelled'),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###
