"""Change the mood_id to false in community_post

Revision ID: 1632b58d1713
Revises: 2ff9507f84e9
Create Date: 2026-08-02 11:10:27.107453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1632b58d1713'
down_revision = '2ff9507f84e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.alter_column('mood_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.alter_column('mood_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
