"""add session_id on the conversations table, and change the supporter_id and request_id to nullable = True

Revision ID: 17762e1c684c
Revises: 05358dff8fa2
Create Date: 2026-09-04 19:45:50.312115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17762e1c684c'
down_revision = '05358dff8fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.alter_column('request_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('supporter_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'counseling_sessions', ['session_id'], ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('supporter_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('request_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
