"""Creating ChatRequest Table

Revision ID: 1b1d6dd4868a
Revises: 2c610aa8f4f1
Create Date: 2026-07-31 23:06:19.419586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1d6dd4868a'
down_revision = '2c610aa8f4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('request_status', sa.Enum('Pending', 'Accepted', 'Rejected', name='chat_request_status_enum'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_requests')
    # ### end Alembic commands ###
