"""addming an updated_at to the moodassessment table

Revision ID: 2ff9507f84e9
Revises: 7b1fa5a4c6b1
Create Date: 2026-08-01 22:20:42.053065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff9507f84e9'
down_revision = '7b1fa5a4c6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_assessments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
