"""initial tables

Revision ID: 39b24650b3a2
Revises: f99ebef76a23
Create Date: 2026-07-30 14:05:30.383446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39b24650b3a2'
down_revision = 'f99ebef76a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Prefer not to say', name='gender_enum'), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'Volunteer', 'Counselor', 'Seeker', name='role_enum'), nullable=False),
    sa.Column('account_status', sa.Enum('Online', 'Offline', name='account_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.subscription_plan_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription_plan_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('occupation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('gender', mysql.ENUM('Male', 'Female', 'Prefer not to say'), nullable=True),
    sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.ENUM('Admin', 'Volunteer', 'Counselor', 'Seeker'), nullable=False),
    sa.Column('account_status', mysql.ENUM('Online', 'Offline'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('update_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.subscription_plan_id'], name=op.f('user_ibfk_1')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.drop_table('users')
    # ### end Alembic commands ###
