"""change the nullable to False

Revision ID: 408172532c2c
Revises: c5488ee43054
Create Date: 2026-08-24 21:59:54.745262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '408172532c2c'
down_revision = 'c5488ee43054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('seeker_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('seeker_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
