"""Adding ChatRequestCreated in the notification.py model enum

Revision ID: 579d4514a6ac
Revises: a2c8a14133b7
Create Date: 2026-09-08 21:23:09.359812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '579d4514a6ac'
down_revision = 'a2c8a14133b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=mysql.ENUM('ChatRequestAccepted', 'CounselingSessionCreated'),
               type_=sa.Enum('ChatRequestCreated', 'ChatRequestAccepted', 'CounselingSessionCreated', name='notification_type_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.Enum('ChatRequestCreated', 'ChatRequestAccepted', 'CounselingSessionCreated', name='notification_type_enum'),
               type_=mysql.ENUM('ChatRequestAccepted', 'CounselingSessionCreated'),
               existing_nullable=False)

    # ### end Alembic commands ###
