"""Counseling session talbe

Revision ID: 5ca0307dafca
Revises: f3e37963a835
Create Date: 2026-08-30 09:55:38.152081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca0307dafca'
down_revision = 'f3e37963a835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counseling_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('counselor_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('Chat', 'Video', name='session_type_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('session_status', sa.Enum('Active', 'Completed', 'Cancelled', name='session_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counseling_sessions')
    # ### end Alembic commands ###
