"""Change the responded to nullable

Revision ID: 7b1fa5a4c6b1
Revises: 1b1d6dd4868a
Create Date: 2026-08-01 00:00:45.548580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b1fa5a4c6b1'
down_revision = '1b1d6dd4868a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_requests', schema=None) as batch_op:
        batch_op.alter_column('responded_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_requests', schema=None) as batch_op:
        batch_op.alter_column('responded_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
