"""Adding attribute session_id to the notification and adding CounselingsessioCreated in the notifiaction

Revision ID: a2c8a14133b7
Revises: 17762e1c684c
Create Date: 2026-09-05 19:43:15.033798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2c8a14133b7'
down_revision = '17762e1c684c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.alter_column('notification_type',
               existing_type=mysql.ENUM('ChatRequestAccepted'),
               type_=sa.Enum('ChatRequestAccepted', 'CounselingSessionCreated', name='notification_type_enum'),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'counseling_sessions', ['session_id'], ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('notification_type',
               existing_type=sa.Enum('ChatRequestAccepted', 'CounselingSessionCreated', name='notification_type_enum'),
               type_=mysql.ENUM('ChatRequestAccepted'),
               existing_nullable=False)
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
