"""Create moodassessment and connect to community post

Revision ID: a8cd2d58166b
Revises: f3e406fc95f6
Create Date: 2026-07-30 23:44:43.249018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8cd2d58166b'
down_revision = 'f3e406fc95f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_assessments',
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Enum('Happy', 'Calm', 'Neutral', 'Anxious', 'Sad', 'Angry', name='mood_enum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mood_id')
    )
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_foreign_key(None, 'mood_assessments', ['mood_id'], ['mood_id'])
        batch_op.drop_column('create_at')
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('create_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('mood_id')

    op.drop_table('mood_assessments')
    # ### end Alembic commands ###
