"""session summary table and relationship with ccounselingsession and sessionsummary

Revision ID: b21ea9f87ea7
Revises: 5ca0307dafca
Create Date: 2026-08-30 18:45:59.013638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21ea9f87ea7'
down_revision = '5ca0307dafca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_summaries',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('counselor_note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['counseling_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_summaries')
    # ### end Alembic commands ###
