"""table for referral

Revision ID: c5488ee43054
Revises: e8428c060f1b
Create Date: 2026-08-24 21:58:12.485267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5488ee43054'
down_revision = 'e8428c060f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('referral_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=True),
    sa.Column('counselor_id', sa.Integer(), nullable=False),
    sa.Column('preferred_session_type', sa.Enum('Chat', 'Video', name='preferred_session_type_enum'), nullable=False),
    sa.Column('volunteer_note', sa.Text(), nullable=False),
    sa.Column('referral_status', sa.Enum('Pending', 'Accepted', 'Rejected', 'Completed', name='referral_status_enum'), nullable=False),
    sa.Column('referred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('referral_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    # ### end Alembic commands ###
