"""Add referral notification type

Revision ID: ef440ccabc03
Revises: f9b87dce4b2f
Create Date: 2026-09-25 20:42:44.182346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef440ccabc03'
down_revision = 'f9b87dce4b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=mysql.ENUM('ChatRequestCreated', 'ChatRequestAccepted', 'ChatRequestRejected', 'CounselingSessionCreated'),
               type_=sa.Enum('ChatRequestCreated', 'ChatRequestAccepted', 'ChatRequestRejected', 'ReferralCreated', 'CounselingSessionCreated', name='notification_type_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.Enum('ChatRequestCreated', 'ChatRequestAccepted', 'ChatRequestRejected', 'ReferralCreated', 'CounselingSessionCreated', name='notification_type_enum'),
               type_=mysql.ENUM('ChatRequestCreated', 'ChatRequestAccepted', 'ChatRequestRejected', 'CounselingSessionCreated'),
               existing_nullable=False)

    # ### end Alembic commands ###
