"""change the nullable of volunteer_note to True

Revision ID: f3e37963a835
Revises: f5611459933a
Create Date: 2026-08-24 22:39:14.289374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3e37963a835'
down_revision = 'f5611459933a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('volunteer_note',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('volunteer_note',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
