"""Create community_post table

Revision ID: f3e406fc95f6
Revises: e3d532dd169d
Create Date: 2026-07-30 22:59:40.594630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3e406fc95f6'
down_revision = 'e3d532dd169d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', mysql.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
