"""Adding ChatRequestRejected in the notification type in notifications table

Revision ID: f9b87dce4b2f
Revises: 30d2f920fcdf
Create Date: 2026-09-11 21:19:10.601390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9b87dce4b2f'
down_revision = '30d2f920fcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=mysql.ENUM('ChatRequestCreated', 'ChatRequestAccepted', 'CounselingSessionCreated'),
               type_=sa.Enum('ChatRequestCreated', 'ChatRequestAccepted', 'ChatRequestRejected', 'CounselingSessionCreated', name='notification_type_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.Enum('ChatRequestCreated', 'ChatRequestAccepted', 'ChatRequestRejected', 'CounselingSessionCreated', name='notification_type_enum'),
               type_=mysql.ENUM('ChatRequestCreated', 'ChatRequestAccepted', 'CounselingSessionCreated'),
               existing_nullable=False)

    # ### end Alembic commands ###
